version: "3"
services:
  movieskart-discovery-service:
    image: anshulgammy/movieskart-discovery-service:1.0-SNAPSHOT
    container_name: movieskart-discovery
    ports:
      - 8705:8705

  movieskart-config-service:
    image: anshulgammy/movieskart-config-service:1.0-SNAPSHOT
    container_name: movieskart-config
    ports:
      - 8706:8706
    links:
      - movieskart-discovery-service

  movieskart-gateway-service:
    image: anshulgammy/movieskart-gateway-service:1.0-SNAPSHOT
    container_name: movieskart-gateway
    ports:
      - 8080:8080
    links:
      - movieskart-discovery-service

  movieskart-metadata-service:
    image: anshulgammy/movieskart-metadata-service:1.0-SNAPSHOT
    container_name: movieskart-metadata
    ports:
      - 8701:8701
    links:
      - movieskart-discovery-service
      - movieskart-config-service
    depends_on:
      - movieskart-discovery-service
      - movieskart-config-service

  movieskart-inventory-service:
    image: anshulgammy/movieskart-inventory-service:1.0-SNAPSHOT
    container_name: movieskart-inventory
    ports:
      - 8702:8702
    links:
      - movieskart-discovery-service
      - movieskart-config-service
    depends_on:
      - movieskart-discovery-service
      - movieskart-config-service

  movieskart-order-service:
    image: anshulgammy/movieskart-order-service:1.0-SNAPSHOT
    container_name: movieskart-order
    ports:
      - 8703:8703
    links:
      - movieskart-discovery-service
      - movieskart-config-service
    depends_on:
      - movieskart-discovery-service
      - movieskart-config-service

  movieskart-orchestrator-service:
    image: anshulgammy/movieskart-orchestrator-service:1.0-SNAPSHOT
    container_name: movieskart-orchestrator
    ports:
      - 8704:8704
    links:
      - movieskart-discovery-service
      - movieskart-config-service
    depends_on:
      - movieskart-discovery-service
      - movieskart-config-service